# Game Period Markets
game_props = (
    'h2h',
    'spreads',
    'totals',
    'outrights',
    'h2h_lay',
    'outrights_lay',
    'alternate_spreads',
    'alternate_totals',
    'btts',
    'draw_no_bet',
    'h2h_3_way',
    'team_totals',
    'alternate_team_totals',
    'h2h_q1',
    'h2h_q2',
    'h2h_q3',
    'h2h_q4',
    'h2h_h1',
    'h2h_h2',
    'h2h_p1',
    'h2h_p2',
    'h2h_p3',
    'h2h_1st_1_innings',
    'h2h_1st_3_innings',
    'h2h_1st_5_innings',
    'h2h_1st_7_innings',
    'h2h_3_way_1st_1_innings',
    'h2h_3_way_1st_3_innings',
    'h2h_3_way_1st_5_innings',
    'h2h_3_way_1st_7_innings',
    'spreads_q1',
    'spreads_q2',
    'spreads_q3',
    'spreads_q4',
    'spreads_h1',
    'spreads_h2',
    'spreads_p1',
    'spreads_p2',
    'spreads_p3',
    'spreads_1st_1_innings',
    'spreads_1st_3_innings',
    'spreads_1st_5_innings',
    'spreads_1st_7_innings',
    'alternate_spreads_1st_5_innings',
    'totals_q1',
    'totals_q2',
    'totals_q3',
    'totals_q4',
    'totals_h1',
    'totals_h2',
    'totals_p1',
    'totals_p2',
    'totals_p3',
    'totals_1st_1_innings',
    'totals_1st_3_innings',
    'totals_1st_5_innings',
    'totals_1st_7_innings',
    'alternate_totals_1st_5_innings'
)

#NFL NCAAF Player Props API
football_player_props = (
    'player_pass_tds',
    'player_pass_yds',
    'player_pass_completions',
    'player_pass_attempts',
    'player_pass_interceptions',
    'player_pass_longest_completion',
    'player_rush_yds',
    'player_rush_attempts',
    'player_rush_longest',
    'player_receptions',
    'player_reception_yds',
    'player_reception_longest',
    'player_kicking_points',
    'player_field_goals',
    'player_tackles_assists',
    'player_1st_td',
    'player_last_td',
    'player_anytime_td'
)

#NBA, NCAAB, WNBA Player Props API
basketball_player_props = (
    'player_points',
    'player_rebounds',
    'player_assists',
    'vvplayer_threes',
    'player_blocks',
    'player_steals',
    'player_blocks_steals',
    'player_turnovers',
    'player_points_rebounds_assists',
    'player_points_rebounds',
    'player_points_assists',
    'player_rebounds_assists',
    'player_first_basket',
    'player_double_double',
    'player_triple_double',
    'player_points_alternate',
    'player_rebounds_alternate',
    'player_assists_alternate',
    'player_blocks_alternate',
    'player_steals_alternate',
    'player_threes_alternate',
    'player_points_assists_alternate',
    'player_points_rebounds_alternate',
    'player_rebounds_assists_alternate',
    'player_points_rebounds_assists_alternate'
)

#MLB Player Props API
baseball_player_props = (
    'batter_home_runs',
    'batter_hits',
    'batter_total_bases',
    'batter_rbis',
    'batter_runs_scored',
    'batter_hits_runs_rbis',
    'batter_singles',
    'batter_doubles',
    'batter_triples',
    'batter_walks',
    'batter_strikeouts',
    'batter_stolen_bases',
    'pitcher_strikeouts',
    'pitcher_record_a_win',
    'pitcher_hits_allowed',
    'pitcher_walks',
    'pitcher_earned_runs',
    'pitcher_outs'
)

#NHL Player Props API
hockey_player_props = (
    'player_points',
    'player_power_play_points',
    'player_assists',
    'player_blocked_shots',
    'player_shots_on_goal',
    'player_total_saves',
    'player_goal_scorer_first',
    'player_goal_scorer_last',
    'player_goal_scorer_anytime'
)
